### ISSUE TITLE
Code using Cassette fails for nightly builds

### ISSUE THREAD

**Issue by j-fu** [JuliaLabs/Cassette.jl#178]
Hi, trying to use sparsity detection using SparseDiffTools,  works with 1.3 and 1.5  but fails on nightly...

See https://travis-ci.org/github/j-fu/VoronoiFVM.jl

(anyway: great stuff, thanks for this!)

**Comment by vchuravy** [comment]
Yeah nightly changes a lot of internals. I haven't gotten around to dive into what we need to change/fix on Cassete site.

**Comment by j-fu** [comment]
Thanks - I'll be patient - have this on `allow_failure`, but just wanted to raise this flag...
