### ISSUE TITLE
Default value to `reflect` should be `Base.current_world`

### ISSUE THREAD

**Issue by vchuravy** [JuliaLabs/Cassette.jl#188]
https://github.com/JuliaLabs/Cassette.jl/blob/52aaf984962747aefb6a4016ff908a4b01ce048e/src/overdub.jl#L77

cc: @maleadt @ChrisRackauckas

**Comment by maleadt** [comment]
ref https://github.com/SciML/DiffEqGPU.jl/pull/104#issuecomment-836402370
